### ISSUE TITLE
Records other than "ewinerysolutions.com" are skipped/not deleted

### ISSUE THREAD

**Issue by ath0mas** [mgatto/cordova-plugin-wkwebview-clearcache#1]
For other devs in cordova community to use this plugin, condition on "ewinerysolutions.com" should be removed ?

https://github.com/mgatto/cordova-plugin-wkwebview-clearcache/blob/ac1f04c7f0fe821415f2b44dfc4c25c79b5dee17/src/ios/WkCacheClear.m#L42-L43

and this same part of the code does not only delete cookies as the param name says, but all data types
see use of `[WKWebsiteDataStore allWebsiteDataTypes]`
it should filter on records with type `WKWebsiteDataTypeCookies` ?

**Comment by mgatto** [comment]
Yes, you're right. Sorry about that. At some point over the holiday break, I'll update it to make it configurable via the JS call and refactor to ensure only the correct type are deleted.

**Comment by mgatto** [comment]
Fixed in 822fcb9
Thanks for the heads up.

**Comment by ath0mas** [comment]
Not tried yet but code change seems ok, Thx!
